### ISSUE TITLE
Shownames with invalid characters

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [adam111316/SickGear#2]
Some shownames have invalid characters (such as \* / ? : etc) because why the fuck not. 
As these characters cant be used in a folder name, on adding existing shows, these will get no results when searching anidb.

Would it be possible to get results somehow when these characters are in the showname, but not in the foldername?

Example shows:
Akatsuki no Yona: The Girl Standing in the Blush of Dawn
Seitokai Yakuindomo *
Fate/Stay Night

**Comment by adam111316** [comment]
![capture](https://cloud.githubusercontent.com/assets/1384040/9980229/2eb11196-5fc3-11e5-92c7-670ad0a2f1c7.PNG)

**Comment by CtrlAltDefeat94** [comment]
If you add Fate/Stay Night as a new show, sg will make a folder for it. That folder is Fate-Stay Night (a dash rather than a forward slash). If you look for Fate-Stay Night, you get no results.

![bpt0nfu 1](https://cloud.githubusercontent.com/assets/5640470/9980286/c6838a84-5f92-11e5-915e-777146617f20.png)

**Comment by adam111316** [comment]
Cheh sif you want fuzzy logic

**Comment by adam111316** [comment]
@CtrlAltDefeat94 plz test

**Comment by CtrlAltDefeat94** [comment]
Seems to be working :D
