### ISSUE TITLE
Start dates on add show page not working

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [adam111316/SickGear#5]
All start on add showpage is always 1st of januari 2001

**Comment by adam111316** [comment]
everyone knows thats when all animes start

**Comment by CtrlAltDefeat94** [comment]
obviously

**Comment by adam111316** [comment]
Don't really see any easy solution to this unfortunately. Probably just going to need to remove the air date from the list and call it fixed.

**Comment by adam111316** [comment]
Lol don't close it yet.  Still need to remove the wrong  airdate
