### ISSUE TITLE
fansubbing groups not loading or loading incorrectly

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [adam111316/SickGear#6]
For charlotte (http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10997), the fansubbing groups arent loading on the edit show page
![iqpvfdx 1](https://cloud.githubusercontent.com/assets/5640470/10041796/3c6e9ab2-61e7-11e5-9735-afeb28796469.png)

Log says no groups are found, but there are groups listed on anidb

LOG:
2015-09-23 05:32:54 DEBUG    Thread-542 :: ANIDB: NetIO < 'T001 325 NO GROUPS FOUND\n'
2015-09-23 05:32:54 DEBUG    TORNADO :: ANIDB: NetIO > 'GROUPSTATUS aid=3486&s=BrFYh&tag=T001'
2015-09-23 05:32:54 DEBUG    TORNADO :: ANIDB: handling(1-2) command GROUPSTATUS

**Comment by adam111316** [comment]
Heh looks like its using the wrong anidb id...

**Comment by CtrlAltDefeat94** [comment]
For Black Rock Shooter (2012) (http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8584&lid=7) I seem to get the wrong groups returned
Anidb:
![aratpnh 1](https://cloud.githubusercontent.com/assets/5640470/10142657/4c44ea64-6614-11e5-917e-6ba03bdded25.png)
SG:
![5oxo6x0 1](https://cloud.githubusercontent.com/assets/5640470/10142669/56fe515c-6614-11e5-86b4-1b71e4ba8e36.png)

**Comment by CtrlAltDefeat94** [comment]
Same goes for "Fate/Stay Night: Unlimited Blade Works (2014)" and Fate/Stay Night: Unlimited Blade Works (2015)

**Comment by adam111316** [comment]
Fixed, please test

**Comment by CtrlAltDefeat94** [comment]
No groups returned for;
High School DxD New: Teishi Kyoushitsu no Vampire (http://anidb.net/perl-bin/animedb.pl?show=anime&aid=11184)

**Comment by adam111316** [comment]
We don't pull in dropped / stalled release groups, so this is working as intended. To get it to display all status types (finished / dropped / stalled etc) would require 6 api calls rather then the one we have now. For the most part stalled is as good as dropped heh.
