### ISSUE TITLE
Yuru yuri S3 won't snatch

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [adam111316/SickGear#8]
Log:
https://gist.github.com/CtrlAltDefeat94/577a1af046f3bff80a15

Maybe I'm screwing something up as it seems to be able to find something

**Comment by adam111316** [comment]
2015-11-12 15:56:08 DEBUG MANUAL-11124 :: [UsenetCrawler] :: Existing episode status: 12804 (Downloaded (720p BluRay))

There is already an existing file

**Comment by CtrlAltDefeat94** [comment]
the showpage didn't list any files for it and the ep was wanted without me setting it so.

Me needing to switch branches with stuff exploding resulting in me reinstalling fixed the issue tho
